//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class news
    {
        public int Id { get; set; }
        public string title { get; set; }
        [AllowHtml]
        [UIHint("tinymce_full")]
        [Display(Name = "content")]
        public string content { get; set; }
        public Nullable<int> status_ { get; set; }
    }
}