//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "vui long nhap ten dang nhap!!!!")]

        public string username { get; set; }
        [Required(ErrorMessage = "Vui long nhap mat khau!!!!")]

        public string password { get; set; }
        [Required(ErrorMessage = "Vui long nhap lai mat khau !!!!")]
        public string confirmpassword { get; set; }
        public string address { get; set; }
        public int role { get; set; }
    }
}
